// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSocialBackend.DataContext;

#nullable disable

namespace RedSocialBackend.Migrations
{
    [DbContext(typeof(RedSocialContext))]
    [Migration("20241123214106_UsuarioBaneado")]
    partial class UsuarioBaneado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RedSocialBackend.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contenido = "Comentario 1",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicacionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Contenido = "Comentario 2",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicacionId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Contenido = "Comentario 3",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicacionId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Contenido = "Comentario 4",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicacionId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Contenido = "Comentario 5",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicacionId = 5,
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("RedSocialBackend.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Configuracion 1",
                            Valor = "Valor 1"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Configuracion 2",
                            Valor = "Valor 2"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Configuracion 3",
                            Valor = "Valor 3"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "Configuracion 4",
                            Valor = "Valor 4"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Configuracion 5",
                            Valor = "Valor 5"
                        });
                });

            modelBuilder.Entity("RedSocialBackend.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            PublicacionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            PublicacionId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            PublicacionId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            PublicacionId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            PublicacionId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            PublicacionId = 5,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            PublicacionId = 2,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            PublicacionId = 3,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            PublicacionId = 1,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 10,
                            Eliminado = false,
                            PublicacionId = 4,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("RedSocialBackend.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "Paraguay"
                        });
                });

            modelBuilder.Entity("RedSocialBackend.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Publicaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contenido = "Publicacion 1",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Contenido = "Publicacion 2",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Contenido = "Publicacion 3",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Contenido = "Publicacion 4",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Contenido = "Publicacion 5",
                            Eliminado = false,
                            Fecha = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("RedSocialBackend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Baneado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreApodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreReal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PaisId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baneado = false,
                            Eliminado = false,
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreApodo = "juanperez",
                            NombreReal = "Juan Perez",
                            PaisId = 1,
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Baneado = false,
                            Eliminado = false,
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreApodo = "marialopez",
                            NombreReal = "Maria Lopez",
                            PaisId = 2,
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Baneado = false,
                            Eliminado = false,
                            FechaNacimiento = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreApodo = "pedroramirez",
                            NombreReal = "Pedro Ramirez",
                            PaisId = 3,
                            Telefono = "456789123"
                        },
                        new
                        {
                            Id = 4,
                            Baneado = false,
                            Eliminado = false,
                            FechaNacimiento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreApodo = "anagarcia",
                            NombreReal = "Ana Garcia",
                            PaisId = 4,
                            Telefono = "789123456"
                        },
                        new
                        {
                            Id = 5,
                            Baneado = false,
                            Eliminado = false,
                            FechaNacimiento = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreApodo = "carlosrodriguez",
                            NombreReal = "Carlos Rodriguez",
                            PaisId = 5,
                            Telefono = "321654987"
                        });
                });

            modelBuilder.Entity("RedSocialBackend.Models.Comentario", b =>
                {
                    b.HasOne("RedSocialBackend.Models.Publicacion", "Publicacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedSocialBackend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedSocialBackend.Models.Like", b =>
                {
                    b.HasOne("RedSocialBackend.Models.Publicacion", "Publicacion")
                        .WithMany("Likes")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedSocialBackend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedSocialBackend.Models.Publicacion", b =>
                {
                    b.HasOne("RedSocialBackend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedSocialBackend.Models.Usuario", b =>
                {
                    b.HasOne("RedSocialBackend.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("RedSocialBackend.Models.Publicacion", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
